// <auto-generated />
using System;
using BookCommerce_API.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCommerce_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230612130648_addCategoryToDb")]
    partial class addCategoryToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCommerce_API.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            DateTimeCreated = new DateTime(2023, 6, 12, 13, 6, 48, 654, DateTimeKind.Utc).AddTicks(4549),
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            DateTimeCreated = new DateTime(2023, 6, 12, 13, 6, 48, 654, DateTimeKind.Utc).AddTicks(4554),
                            DisplayOrder = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 3,
                            DateTimeCreated = new DateTime(2023, 6, 12, 13, 6, 48, 654, DateTimeKind.Utc).AddTicks(4555),
                            DisplayOrder = 4,
                            Name = "SciFi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
